---
- name: Download Go
  get_url: url="https://storage.googleapis.com/golang/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
           dest="/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"

- name: Extract and install Go
  unarchive: src="/usr/local/src/go{{ golang_version }}.{{ golang_os }}-{{ golang_arch }}.tar.gz"
             dest=/usr/local/
             copy=no

- name: Symlink Go into /usr/local/bin
  file: src="/usr/local/go/bin/{{ item }}"
        dest="/usr/local/bin/{{ item }}"
        state=link
  with_items:
    - go
    - godoc
    - gofmt

- name: Install Godep
  command: go get github.com/tools/godep
           creates="{{ golang_path }}/bin/godep"
  environment:
    GOPATH: "{{ golang_path }}"

- name: Set environment variables in .bashrc
  lineinfile:
    dest=/home/{{ golang_user }}/.bashrc
    state=present
    line="export {{ item.var }}={{ item.value }}"
  with_items:
    - { var: "GOOS", value: "{{ golang_os }}" }
    - { var: "GOARCH", value: "{{ golang_arch }}" }
    - { var: "GOROOT", value: "/usr/local/go" }
    - { var: "GOPATH", value: "{{ golang_path }}" }
